
export const JOKE_CREATE = 'JOKE_CREATE';
export const JOKE_LIKE = 'JOKE_LIKE';
export const JOKE_DELETE = 'JOKE_DELETE';
export const JOKES_LOAD = 'JOKES_LOAD';

export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';

export const ERROR_DISPLAY_ON = 'ERROR_DISPLAY_ON';
export const ERROR_DISPLAY_OFF = 'ERROR_DISPLAY_OFF';

export const OPEN_SELECTED = 'OPEN_SELECTED';